MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
  SELF_SUPERVISOR:
    OSHOT_ITERATIONS: 5
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval",)
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (5000, )
  MAX_ITER: 80000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: "outputs/VOC_baseline_bn"
